### PR TITLE
latest IP data, 531380 records, updated on 21 Jun 2023

### PR DESCRIPTION
**Pull request by AvenSun**
find nowhere to upload, so make this PR.
data was extracted from file released by cn88. net.

### CODE REVIEW

**Comment by nnhy** [comment]
http://x.newlifex.com/ip.gz

uploaded!

**Comment by AvenSun** [comment]
@nnhy 

ip

It seems that ip.gz saved via the link above is still the old one.

**Comment by nnhy** [comment]
Maybe it's because the CDN has cached this file.
You need to delete this file from the local “Data” directory.

image

**Comment by AvenSun** [comment]
I see. thanks!

**Pull request merged**
